apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      name: client-deployment
      labels:
        app: client
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
