apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    app: client
spec:
  containers:
    - name: web
      image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: web-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: client
  ports:
    - name: web
      protocol: TCP
      targetPort: 80
      port: 8080
