apiVersion: v1
kind: Service
metadata:
  name: web-server-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: 80
