apiVersion: v1
kind: Pod
metadata:
  name: webserver
  labels:
    app: webapp
spec:
  containers:
    - image: nginx
      name: webserver
---
apiVersion: v1
kind: Service
metadata:
  name: webserver-loadbalancer-service
spec:
  selector:
    app: webapp
  type: LoadBalancer
  ports:
    - name: webserver
      protocol: TCP
      port: 8080
      targetPort: 80
